/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class Medicine extends javax.swing.JFrame {

    /**
     * Creates new form Medicine
     */
    public Medicine() {
        initComponents();
        
         selectMed();
         GetCategory();
         GetCompany();
         
    }

    Connection con=null;
    Statement st=null;
    ResultSet  Rs=null;
    
    java.util.Date EXP;
    java.sql.Date myexpdate;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        medi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cati = new javax.swing.JLabel();
        mexi = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        meq = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        meni = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        QUANTITY = new javax.swing.JTextField();
        MED_NAME = new javax.swing.JTextField();
        EXP_DATE = new com.toedter.calendar.JDateChooser();
        MED_ID = new javax.swing.JTextField();
        STATUS = new javax.swing.JTextField();
        BADGE_NO = new javax.swing.JTextField();
        MED_COMPANY = new javax.swing.JComboBox<>();
        REMARKS = new javax.swing.JTextField();
        MED_PRICE = new javax.swing.JTextField();
        ADDbtn = new javax.swing.JButton();
        CLEARBTN = new javax.swing.JButton();
        UPDATEbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MedicineTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        MED_CAT = new javax.swing.JComboBox<>();
        DELETEBTN1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 28, 92));

        medi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        medi.setForeground(new java.awt.Color(32, 28, 92));
        medi.setText("MED_ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(32, 28, 92));
        jLabel5.setText("MANAGE MEDICINE");

        cati.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cati.setForeground(new java.awt.Color(32, 28, 92));
        cati.setText("MED_CAT");

        mexi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mexi.setForeground(new java.awt.Color(32, 28, 92));
        mexi.setText("MED_EXP");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(32, 28, 92));
        jLabel8.setText("PRICE");

        meq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meq.setForeground(new java.awt.Color(32, 28, 92));
        meq.setText("QUANTITY");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(32, 28, 92));
        jLabel10.setText("COMPANY");

        meni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meni.setForeground(new java.awt.Color(32, 28, 92));
        meni.setText("MED_NAME");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(32, 28, 92));
        jLabel12.setText("REMARKS");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(32, 28, 92));
        jLabel13.setText("STATUS");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(32, 28, 92));
        jLabel15.setText("BADGE_NO");

        QUANTITY.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        QUANTITY.setForeground(new java.awt.Color(32, 28, 92));

        MED_NAME.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MED_NAME.setForeground(new java.awt.Color(32, 28, 92));

        MED_ID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MED_ID.setForeground(new java.awt.Color(32, 28, 92));

        STATUS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        STATUS.setForeground(new java.awt.Color(32, 28, 92));

        BADGE_NO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BADGE_NO.setForeground(new java.awt.Color(32, 28, 92));

        REMARKS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        REMARKS.setForeground(new java.awt.Color(32, 28, 92));

        MED_PRICE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MED_PRICE.setForeground(new java.awt.Color(32, 28, 92));

        ADDbtn.setBackground(new java.awt.Color(32, 28, 92));
        ADDbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ADDbtn.setForeground(new java.awt.Color(255, 204, 51));
        ADDbtn.setText("ADD");
        ADDbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDbtnMouseClicked(evt);
            }
        });
        ADDbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDbtnActionPerformed(evt);
            }
        });

        CLEARBTN.setBackground(new java.awt.Color(32, 28, 92));
        CLEARBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CLEARBTN.setForeground(new java.awt.Color(255, 204, 51));
        CLEARBTN.setText("CLEAR");
        CLEARBTN.setActionCommand("");
        CLEARBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLEARBTNMouseClicked(evt);
            }
        });

        UPDATEbtn.setBackground(new java.awt.Color(32, 28, 92));
        UPDATEbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UPDATEbtn.setForeground(new java.awt.Color(255, 204, 51));
        UPDATEbtn.setText("UPDATE");
        UPDATEbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPDATEbtnMouseClicked(evt);
            }
        });

        MedicineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Medicine_Id", "Med_Name", "Quantity", "Company", "Badge_No", "Remarks", "Status", "Expery", "Price", "Category"
            }
        ));
        MedicineTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicineTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MedicineTable);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(32, 28, 92));
        jLabel16.setText("MEDICINE LIST");

        DELETEBTN1.setBackground(new java.awt.Color(32, 28, 92));
        DELETEBTN1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DELETEBTN1.setForeground(new java.awt.Color(255, 204, 51));
        DELETEBTN1.setText("DELETE");
        DELETEBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEBTN1MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(32, 28, 92));
        jLabel7.setText("x");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meni)
                    .addComponent(mexi)
                    .addComponent(medi)
                    .addComponent(cati))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MED_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EXP_DATE, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(MED_CAT, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MED_NAME, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                    .addComponent(ADDbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel5))
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(meq)
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(MED_COMPANY, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(QUANTITY, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BADGE_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(REMARKS, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(UPDATEbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(DELETEBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel16)
                        .addGap(172, 172, 172)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MED_PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CLEARBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5))
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ADDbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UPDATEbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DELETEBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CLEARBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medi)
                            .addComponent(meq)
                            .addComponent(jLabel13)
                            .addComponent(QUANTITY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MED_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cati, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(MED_COMPANY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MED_CAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BADGE_NO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel8)
                                    .addComponent(MED_PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(meni))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MED_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(mexi))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(REMARKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EXP_DATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("CATEGORY");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("PARTY");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 51));
        jLabel3.setText("SELLING");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(302, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void selectMed(){
    
        try{
//    con=DriverManager.getConnection("jdbc:derby://localhost:1527/pharma","saud","saud123");
//    st=con.createStatement();
//    Rs=(ResulSet) st.executeQuery("SELECT * FROM SAUD.MEDICINE");
//    MedicineTable.setModel(DbUtils.resultSetToTableModel((ResultSet) Rs));

con=DriverManager.getConnection("jdbc:derby://localhost:1527/pharma","saud","saud123");
st=con.createStatement();
Rs= st.executeQuery("SELECT * FROM SAUD.MEDICINE");
MedicineTable.setModel(DbUtils.resultSetToTableModel( Rs));
    
    
        }
        
        catch(SQLException e){
        
            e.printStackTrace();
        }
    }
    
    
    
    private void ADDbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDbtnActionPerformed
        // TODO add your handling code here:
        
        
       
    }//GEN-LAST:event_ADDbtnActionPerformed

    private void ADDbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDbtnMouseClicked
        // TODO add your handling code here:
        
        
         EXP=EXP_DATE.getDate();
        myexpdate=new java.sql.Date(EXP.getTime());
        
        
        try{

            con=DriverManager.getConnection("jdbc:derby://localhost:1527/pharma","saud","saud123");
            PreparedStatement add=con.prepareStatement("insert into MEDICINE values(?,?,?,?,?,?,?,?,?,?)");
            
            add.setInt(1,Integer.valueOf(MED_ID.getText()));
            add.setString(2, MED_NAME.getText());
            add.setInt(3,Integer.valueOf(QUANTITY.getText()));
          add.setInt(4, Integer.valueOf(BADGE_NO.getText()));
            add.setString(5, REMARKS.getText());
            add.setInt(6, Integer.valueOf(STATUS.getText()));
             add.setDouble(7, Double.valueOf(MED_PRICE.getText()));
            add.setDate(8, myexpdate);            
            add.setString(9, MED_CAT.getSelectedItem().toString());
            add.setString(10, MED_COMPANY.getSelectedItem().toString());
            
            int row=add.executeUpdate();
            JOptionPane.showMessageDialog(this,"Medicines added successfully....");
             con.close();
             
             selectMed();
            
        }
        
        catch(SQLException e){
        
            e.printStackTrace();
        }
    }//GEN-LAST:event_ADDbtnMouseClicked

    private void CLEARBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLEARBTNMouseClicked
        // TODO add your handling code here:


      MED_ID.setText("");
      MED_NAME.setText("");
      QUANTITY.setText("");
      BADGE_NO.setText("");
      REMARKS.setText("");
      STATUS.setText("");
      MED_PRICE.setText("");
     
            
            

    }//GEN-LAST:event_CLEARBTNMouseClicked

    private void MedicineTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicineTableMouseClicked
        // TODO add your handling code here:

        DefaultTableModel model=(DefaultTableModel)MedicineTable.getModel();
        int myindex=MedicineTable.getSelectedRow();
        MED_ID.setText(model.getValueAt(myindex, 0).toString());
        MED_NAME.setText(model.getValueAt(myindex, 1).toString());
        QUANTITY.setText(model.getValueAt(myindex, 2).toString());
        BADGE_NO.setText(model.getValueAt(myindex, 3).toString());
        REMARKS.setText(model.getValueAt(myindex, 4).toString());
        STATUS.setText(model.getValueAt(myindex, 5).toString());
        MED_PRICE.setText(model.getValueAt(myindex, 6).toString());
        
        
        

    }//GEN-LAST:event_MedicineTableMouseClicked

    private void UPDATEbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEbtnMouseClicked
        // TODO add your handling code here:


        if(MED_ID.getText().isEmpty()||MED_NAME.getText().isEmpty()||QUANTITY.getText().isEmpty() ||BADGE_NO.getText().isEmpty()||REMARKS.getText().isEmpty()||STATUS.getText().isEmpty()||MED_PRICE.getText().isEmpty())
        {
           JOptionPane.showMessageDialog(this, "Missing information .....");
            
        }
        
        else{
            try{
                String idd=MED_ID.getText();
                int id=Integer.parseInt(idd);
                
                String qq=QUANTITY.getText();
                int quantity=Integer.parseInt(qq);
                
                
                
                String bb=BADGE_NO.getText();
                int badge=Integer.parseInt(bb);
                
                String ss=STATUS.getText();
                int status=Integer.parseInt(ss);
                
                String mp=MED_PRICE.getText();
                int price=Integer.parseInt(mp);
                
                
                
                
            
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/pharma","saud","saud123");
             EXP=EXP_DATE.getDate();
        myexpdate=new java.sql.Date(EXP.getTime());
        
        String updatequery ="Update SAUD.MEDICINE set MED_NAME = '"+MED_NAME.getText()+"'"+",QUANTITY = "+quantity+",BADGE_NO = "+badge+",REMARKS = '"+REMARKS.getText()+"'"+",STATUS = "+status+",MED_PRICE = "+price+",EXP_DATE = '"+myexpdate+"'"+",MED_CAT = '"+MED_CAT.getSelectedItem().toString()+"'"+",MED_COMPANY = '"+MED_COMPANY.getSelectedItem().toString()+"'"+"where MED_ID = "+id;
        Statement Add=con.createStatement();
        Add.executeUpdate(updatequery);
         JOptionPane.showMessageDialog(this, "Medicine updated successfully.....");
        
            
            }
        
        
            catch(SQLException e){
            
                
            e.printStackTrace();
        
            }
           selectMed(); 
        }

    }//GEN-LAST:event_UPDATEbtnMouseClicked

    private void DELETEBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEBTN1MouseClicked
        // TODO add your handling code here:
         if(MED_ID.getText().isEmpty()){
       
           JOptionPane.showMessageDialog(this,"Enter medicine to be deleted.....");
       }
       else{
       
           try{
           
               con=DriverManager.getConnection("jdbc:derby://localhost:1527/pharma","saud","saud123");
               String id=MED_ID.getText();
               String Query="DELETE FROM SAUD.MEDICINE where MED_ID="+id;
               Statement add=con.createStatement();
               add.executeUpdate(Query);
            
               selectMed();
           
        JOptionPane.showMessageDialog(this, "Medicine deleted successfully.....");
           }
           catch(SQLException e){
           
               e.printStackTrace();
           }
       }
    }//GEN-LAST:event_DELETEBTN1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
        
        
        
        new Category().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
        
        new Party().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked
    
    public void  GetCategory(){
    
    try{
        
        con=DriverManager.getConnection("jdbc:derby://localhost:1527/pharma","saud","saud123");
st=con.createStatement();
Rs= st.executeQuery("SELECT * FROM SAUD.CATEGORY");
    
        while(Rs.next()){
        
            String cat=Rs.getString("CATEGORY_NAME");
            MED_CAT.addItem(cat);
        
        }


    }
    catch(SQLException e){
        
        e.printStackTrace();
    }}
     public void  GetCompany(){
    
    try{
        
        con=DriverManager.getConnection("jdbc:derby://localhost:1527/pharma","saud","saud123");
st=con.createStatement();
Rs= st.executeQuery("SELECT * FROM SAUD.CATEGORY");
    
        while(Rs.next()){
        
            String cat=Rs.getString("COMPANY");
            MED_COMPANY.addItem(cat);
        
        }


    }
    catch(SQLException e){
        
        e.printStackTrace();
    }}
    
   
    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
        new SELLING().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDbtn;
    private javax.swing.JTextField BADGE_NO;
    private javax.swing.JButton CLEARBTN;
    private javax.swing.JButton DELETEBTN1;
    private com.toedter.calendar.JDateChooser EXP_DATE;
    private javax.swing.JComboBox<String> MED_CAT;
    private javax.swing.JComboBox<String> MED_COMPANY;
    private javax.swing.JTextField MED_ID;
    private javax.swing.JTextField MED_NAME;
    private javax.swing.JTextField MED_PRICE;
    private javax.swing.JTable MedicineTable;
    private javax.swing.JTextField QUANTITY;
    private javax.swing.JTextField REMARKS;
    private javax.swing.JTextField STATUS;
    private javax.swing.JButton UPDATEbtn;
    private javax.swing.JLabel cati;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel medi;
    private javax.swing.JLabel meni;
    private javax.swing.JLabel meq;
    private javax.swing.JLabel mexi;
    // End of variables declaration//GEN-END:variables
}
